-- Create the holdings table
CREATE TABLE IF NOT EXISTS public.holdings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  symbol TEXT NOT NULL,
  name TEXT,
  quantity NUMERIC NOT NULL,
  cost_basis NUMERIC,
  current_price NUMERIC NOT NULL,
  currency TEXT DEFAULT 'USD',
  institution_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Constraint to ensure we don't duplicate holdings for the same symbol/user
  UNIQUE(user_id, symbol)
);

-- Enable Row Level Security
ALTER TABLE public.holdings ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can only see their own holdings
CREATE POLICY "Users can view their own holdings"
ON public.holdings FOR SELECT
USING (auth.uid() = user_id);

-- RLS Policy: Users can insert their own holdings
CREATE POLICY "Users can insert their own holdings"
ON public.holdings FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- RLS Policy: Users can update their own holdings
CREATE POLICY "Users can update their own holdings"
ON public.holdings FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own holdings" 
ON public.holdings FOR UPDATE 
USING (auth.uid() = user_id);
