import os
from dotenv import load_dotenv

def audit_env():
    """
    Audits environment variables for Plaid and SnapTrade integration.
    Generates docs/env_audit_plaid_snaptrade.md
    """
    # Load env vars from .env if it exists, but we also want to check what's actually loaded
    load_dotenv()

    report_lines = []
    report_lines.append("# Environment Audit: Plaid & SnapTrade")
    report_lines.append("\nGenerated by audit script.\n")

    # --- Plaid Audit ---
    report_lines.append("## Section 1 – Plaid Config")

    plaid_vars = [
        "PLAID_ENV",
        "PLAID_CLIENT_ID",
        "PLAID_SECRET",
    ]

    missing_plaid = []

    for var in plaid_vars:
        val = os.getenv(var)
        status = ""
        if not val:
            status = "❌ MISSING / UNDEFINED"
            missing_plaid.append(var)
        elif "test" in val.lower() or "sandbox" in val.lower() or "mock" in val.lower():
            status = f"⚠️  Looks like test/sandbox (Value: {val[:4]}...)"
        elif var == "PLAID_ENV" and val.lower() != "production":
            status = f"⚠️  Not set to 'production' (Value: {val})"
        else:
            status = "✅ Correct & Live (Appears to be)"

        report_lines.append(f"- **{var}**: {status}")

    # --- SnapTrade Audit ---
    report_lines.append("\n## Section 2 – SnapTrade Config")

    snap_vars = [
        "SNAPTRADE_CLIENT_ID",
        "SNAPTRADE_CONSUMER_KEY",
        "SNAPTRADE_ENV",
        "SNAPTRADE_BASE_URL"
    ]

    missing_snap = []

    for var in snap_vars:
        val = os.getenv(var)
        status = ""
        if not val:
            if var == "SNAPTRADE_BASE_URL":
                 status = "ℹ️  Optional (Defaulting to prod URL)"
            else:
                status = "❌ MISSING / UNDEFINED"
                missing_snap.append(var)
        elif "test" in val.lower() or "demo" in val.lower():
            status = f"⚠️  Looks like test/demo (Value: {val[:4]}...)"
        elif var == "SNAPTRADE_ENV" and val.lower() != "production":
             status = f"⚠️  Not set to 'production' (Value: {val})"
        else:
            status = "✅ Correct & Live (Appears to be)"

        report_lines.append(f"- **{var}**: {status}")

    # --- Actionable Items ---
    report_lines.append("\n## Section 3 – Actionable “What’s missing / to fix”")

    if not missing_plaid and not missing_snap:
        report_lines.append("- ✅ No missing required environment variables.")

    if missing_plaid:
        for m in missing_plaid:
            report_lines.append(f"- [ ] Set `{m}` in .env (Production value needed for live app)")

    if missing_snap:
        for m in missing_snap:
            report_lines.append(f"- [ ] Set `{m}` in .env for SnapTrade integration")

    # Check for test values in prod context
    app_env = os.getenv("APP_ENV", "development")
    if app_env == "production":
        # Strict check
        if os.getenv("PLAID_ENV") != "production":
             report_lines.append("- [ ] **CRITICAL**: `PLAID_ENV` is not 'production' but `APP_ENV` is production.")
        if os.getenv("SNAPTRADE_ENV") != "production":
             report_lines.append("- [ ] **CRITICAL**: `SNAPTRADE_ENV` is not 'production'.")

    return "\n".join(report_lines)

if __name__ == "__main__":
    report = audit_env()
    print(report)

    # Write to file
    os.makedirs("docs", exist_ok=True)
    with open("docs/env_audit_plaid_snaptrade.md", "w", encoding="utf-8") as f:
        f.write(report)
    print("\nAudit report written to docs/env_audit_plaid_snaptrade.md")
