-- supabase/migrations/20221127155800_create_trade_journal_table.sql

CREATE TABLE IF NOT EXISTS public.trade_journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    symbol TEXT NOT NULL,
    strategy TEXT,
    entry_date TIMESTAMP WITH TIME ZONE NOT NULL,
    entry_price DOUBLE PRECISION,
    strikes TEXT,
    dte INTEGER,
    iv_rank DOUBLE PRECISION,
    max_gain DOUBLE PRECISION,
    max_loss DOUBLE PRECISION,
    notes TEXT,
    status TEXT DEFAULT 'open'::text NOT NULL,
    exit_date TIMESTAMP WITH TIME ZONE,
    exit_price DOUBLE PRECISION,
    pnl DOUBLE PRECISION,
    pnl_pct DOUBLE PRECISION,
    source TEXT -- e.g., 'optimizer', 'scout', 'manual'
);

ALTER TABLE public.trade_journal_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to access their own journal entries"
ON public.trade_journal_entries
FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

COMMENT ON TABLE public.trade_journal_entries IS 'Stores user trade journal entries for analysis and review.';
COMMENT ON COLUMN public.trade_journal_entries.source IS 'The origin of the trade idea (e.g., optimizer, scout, manual).';
