-- Migration: Security v3 RLS Hardening
-- Enable Row Level Security (RLS) on all user-scoped tables and enforce ownership policies.
-- Uses DO blocks to guard against missing tables during fresh bootstrap.
-- Uses DROP POLICY IF EXISTS + CREATE POLICY pattern for idempotency.

-- 1. positions
DO $$
BEGIN
  IF to_regclass('public.positions') IS NOT NULL THEN
    ALTER TABLE positions ENABLE ROW LEVEL SECURITY;

    DROP POLICY IF EXISTS "Users can view own positions" ON positions;
    CREATE POLICY "Users can view own positions" ON positions
        FOR SELECT USING (auth.uid() = user_id);

    DROP POLICY IF EXISTS "Users can update own positions" ON positions;
    CREATE POLICY "Users can update own positions" ON positions
        FOR UPDATE USING (auth.uid() = user_id);

    DROP POLICY IF EXISTS "Users can insert own positions" ON positions;
    CREATE POLICY "Users can insert own positions" ON positions
        FOR INSERT WITH CHECK (auth.uid() = user_id);

    DROP POLICY IF EXISTS "Users can delete own positions" ON positions;
    CREATE POLICY "Users can delete own positions" ON positions
        FOR DELETE USING (auth.uid() = user_id);
  END IF;
END $$;


-- 2. trade_suggestions
DO $$
BEGIN
  IF to_regclass('public.trade_suggestions') IS NOT NULL THEN
    ALTER TABLE trade_suggestions ENABLE ROW LEVEL SECURITY;

    DROP POLICY IF EXISTS "Users can view own suggestions" ON trade_suggestions;
    CREATE POLICY "Users can view own suggestions" ON trade_suggestions
        FOR SELECT USING (auth.uid() = user_id);

    DROP POLICY IF EXISTS "Users can update own suggestions" ON trade_suggestions;
    CREATE POLICY "Users can update own suggestions" ON trade_suggestions
        FOR UPDATE USING (auth.uid() = user_id);

    -- Normally generated by system/admin, but if user triggers rebalance, they insert.
    DROP POLICY IF EXISTS "Users can insert own suggestions" ON trade_suggestions;
    CREATE POLICY "Users can insert own suggestions" ON trade_suggestions
        FOR INSERT WITH CHECK (auth.uid() = user_id);

    DROP POLICY IF EXISTS "Users can delete own suggestions" ON trade_suggestions;
    CREATE POLICY "Users can delete own suggestions" ON trade_suggestions
        FOR DELETE USING (auth.uid() = user_id);
  END IF;
END $$;


-- 3. weekly_trade_reports
DO $$
BEGIN
  IF to_regclass('public.weekly_trade_reports') IS NOT NULL THEN
    ALTER TABLE weekly_trade_reports ENABLE ROW LEVEL SECURITY;

    DROP POLICY IF EXISTS "Users can view own reports" ON weekly_trade_reports;
    CREATE POLICY "Users can view own reports" ON weekly_trade_reports
        FOR SELECT USING (auth.uid() = user_id);

    -- Reports usually generated by system tasks (service_role), so user insert/update might not be needed.
    -- But allowing it for flexibility if they re-run report manually.
    DROP POLICY IF EXISTS "Users can manage own reports" ON weekly_trade_reports;
    CREATE POLICY "Users can manage own reports" ON weekly_trade_reports
        FOR ALL USING (auth.uid() = user_id);
  END IF;
END $$;


-- 4. user_settings
DO $$
BEGIN
  IF to_regclass('public.user_settings') IS NOT NULL THEN
    ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;

    DROP POLICY IF EXISTS "Users can view own settings" ON user_settings;
    CREATE POLICY "Users can view own settings" ON user_settings
        FOR SELECT USING (auth.uid() = user_id);

    DROP POLICY IF EXISTS "Users can update own settings" ON user_settings;
    CREATE POLICY "Users can update own settings" ON user_settings
        FOR UPDATE USING (auth.uid() = user_id);

    DROP POLICY IF EXISTS "Users can insert own settings" ON user_settings;
    CREATE POLICY "Users can insert own settings" ON user_settings
        FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;


-- 5. analytics_events
DO $$
BEGIN
  IF to_regclass('public.analytics_events') IS NOT NULL THEN
    ALTER TABLE analytics_events ENABLE ROW LEVEL SECURITY;

    DROP POLICY IF EXISTS "Users can insert own analytics events" ON analytics_events;
    CREATE POLICY "Users can insert own analytics events" ON analytics_events
        FOR INSERT WITH CHECK (auth.uid() = user_id);

    DROP POLICY IF EXISTS "Users can view own analytics events" ON analytics_events;
    CREATE POLICY "Users can view own analytics events" ON analytics_events
        FOR SELECT USING (auth.uid() = user_id);
  END IF;
END $$;


-- 6. learning_feedback_loops
DO $$
BEGIN
  IF to_regclass('public.learning_feedback_loops') IS NOT NULL THEN
    ALTER TABLE learning_feedback_loops ENABLE ROW LEVEL SECURITY;

    DROP POLICY IF EXISTS "Users can view own feedback loops" ON learning_feedback_loops;
    CREATE POLICY "Users can view own feedback loops" ON learning_feedback_loops
        FOR SELECT USING (auth.uid() = user_id);

    DROP POLICY IF EXISTS "Users can insert/update own feedback loops" ON learning_feedback_loops;
    CREATE POLICY "Users can insert/update own feedback loops" ON learning_feedback_loops
        FOR ALL USING (auth.uid() = user_id);
  END IF;
END $$;


-- 7. portfolio_snapshots
DO $$
BEGIN
  IF to_regclass('public.portfolio_snapshots') IS NOT NULL THEN
    ALTER TABLE portfolio_snapshots ENABLE ROW LEVEL SECURITY;

    DROP POLICY IF EXISTS "Users can view own snapshots" ON portfolio_snapshots;
    CREATE POLICY "Users can view own snapshots" ON portfolio_snapshots
        FOR SELECT USING (auth.uid() = user_id);

    DROP POLICY IF EXISTS "Users can insert own snapshots" ON portfolio_snapshots;
    CREATE POLICY "Users can insert own snapshots" ON portfolio_snapshots
        FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;


-- 8. plaid_items (Sensitive)
DO $$
BEGIN
  IF to_regclass('public.plaid_items') IS NOT NULL THEN
    ALTER TABLE plaid_items ENABLE ROW LEVEL SECURITY;

    DROP POLICY IF EXISTS "Users can view own plaid items" ON plaid_items;
    CREATE POLICY "Users can view own plaid items" ON plaid_items
        FOR SELECT USING (auth.uid() = user_id);

    DROP POLICY IF EXISTS "Users can delete own plaid items" ON plaid_items;
    CREATE POLICY "Users can delete own plaid items" ON plaid_items
        FOR DELETE USING (auth.uid() = user_id);
  END IF;
END $$;

-- Note: plaid_items usually managed via backend tasks or secure endpoints.
-- Allowing insert via RLS is fine if `user_id` matches.

-- Service Role (Admin) Bypasses RLS by default in Supabase.
-- Explicit policies for service role are NOT required as long as `bypass rls` attribute is set on the role,
-- which is standard for `service_role`.
