ALTER TABLE public.learning_feedback_loops
ADD COLUMN IF NOT EXISTS strategy TEXT NULL,
ADD COLUMN IF NOT EXISTS "window" TEXT NULL,
ADD COLUMN IF NOT EXISTS total_trades INTEGER NULL,
ADD COLUMN IF NOT EXISTS wins INTEGER NULL,
ADD COLUMN IF NOT EXISTS losses INTEGER NULL,
ADD COLUMN IF NOT EXISTS avg_return NUMERIC NULL,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NULL;
