-- Migration: Security v3 RLS Hardening
-- Enable Row Level Security (RLS) on all user-scoped tables and enforce ownership policies.

-- 1. positions
ALTER TABLE positions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own positions" ON positions
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update own positions" ON positions
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own positions" ON positions
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own positions" ON positions
    FOR DELETE USING (auth.uid() = user_id);


-- 2. trade_suggestions
ALTER TABLE trade_suggestions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own suggestions" ON trade_suggestions
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update own suggestions" ON trade_suggestions
    FOR UPDATE USING (auth.uid() = user_id);

-- Normally generated by system/admin, but if user triggers rebalance, they insert.
CREATE POLICY "Users can insert own suggestions" ON trade_suggestions
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own suggestions" ON trade_suggestions
    FOR DELETE USING (auth.uid() = user_id);


-- 3. weekly_trade_reports
ALTER TABLE weekly_trade_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own reports" ON weekly_trade_reports
    FOR SELECT USING (auth.uid() = user_id);

-- Reports usually generated by system tasks (service_role), so user insert/update might not be needed.
-- But allowing it for flexibility if they re-run report manually.
CREATE POLICY "Users can manage own reports" ON weekly_trade_reports
    FOR ALL USING (auth.uid() = user_id);


-- 4. user_settings
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own settings" ON user_settings
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update own settings" ON user_settings
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own settings" ON user_settings
    FOR INSERT WITH CHECK (auth.uid() = user_id);


-- 5. analytics_events
ALTER TABLE analytics_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert own analytics events" ON analytics_events
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view own analytics events" ON analytics_events
    FOR SELECT USING (auth.uid() = user_id);


-- 6. learning_feedback_loops
ALTER TABLE learning_feedback_loops ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own feedback loops" ON learning_feedback_loops
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert/update own feedback loops" ON learning_feedback_loops
    FOR ALL USING (auth.uid() = user_id);


-- 7. portfolio_snapshots
ALTER TABLE portfolio_snapshots ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own snapshots" ON portfolio_snapshots
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own snapshots" ON portfolio_snapshots
    FOR INSERT WITH CHECK (auth.uid() = user_id);


-- 8. plaid_items (Sensitive)
ALTER TABLE plaid_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own plaid items" ON plaid_items
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own plaid items" ON plaid_items
    FOR DELETE USING (auth.uid() = user_id);

-- Note: plaid_items usually managed via backend tasks or secure endpoints.
-- Allowing insert via RLS is fine if `user_id` matches.

-- Service Role (Admin) Bypasses RLS by default in Supabase.
-- Explicit policies for service role are NOT required as long as `bypass rls` attribute is set on the role,
-- which is standard for `service_role`.
