-- =============================================================================
-- Seed transaction: 50 approved policy_registrations (small_tier_v1)
-- =============================================================================
-- NOT APPLIED BY THIS PR. Operator applies via the migration procedure.
--
-- Generated from packages/quantum/policy_lab/fleet_policy_design.py
-- (py -3.11 -m packages.quantum.policy_lab.fleet_policy_design). Requires
-- the 20260719000000_policy_registrations migration to be applied first.
--
-- config_hash is DERIVED here (never client-invented): the INSERT computes
-- encode(extensions.digest(config_canonical,'sha256'),'hex') inside the
-- transaction. pgcrypto is installed (schema `extensions`, verified via MCP).
-- The post-commit DO block re-asserts: exactly 50 rows, 50 distinct hashes,
-- 50 distinct canonical strings, and hash==sha256(canonical) for every row —
-- any failure RAISEs and rolls the whole seed back.
-- =============================================================================

BEGIN;

INSERT INTO policy_registrations (
    policy_registration_id, policy_family, anchor_lineage,
    policy_config, config_canonical, config_hash,
    schema_version, approval_status, effective_epoch,
    changed_axes, design_rationale, created_at, approved_at, created_by
)
SELECT
    v.policy_registration_id, v.policy_family, v.anchor_lineage,
    v.config_canonical::jsonb, v.config_canonical,
    encode(extensions.digest(v.config_canonical, 'sha256'), 'hex'),
    1, 'approved', v.effective_epoch,
    v.changed_axes::jsonb, v.design_rationale, now(), now(), v.created_by
FROM (VALUES
    ('aggressive_anchor', 'aggressive', 'aggressive_anchor', '{"budget_cap_pct":0.35,"max_dte_to_enter":45,"max_positions_open":4,"max_risk_pct_per_trade":0.035,"max_suggestions_per_day":4,"min_dte_to_exit":7,"min_score_threshold":30.0,"risk_multiplier":1.2,"sizing_method":"budget_proportional","stop_loss_pct":0.3,"target_profit_pct":0.5}', 'small_tier_v1', '[]', 'Anchor: verbatim policy_lab_cohorts.policy_config for the aggressive cohort (live champion (policy_lab_cohorts.promoted_at 2026-05-18)); no axis varied.', 'fable_orchestrator_lane_a'),
    ('neutral_anchor', 'neutral', 'neutral_anchor', '{"budget_cap_pct":0.3,"max_dte_to_enter":45,"max_positions_open":3,"max_risk_pct_per_trade":0.025,"max_suggestions_per_day":3,"min_dte_to_exit":10,"min_score_threshold":50.0,"risk_multiplier":1.0,"sizing_method":"budget_proportional","stop_loss_pct":0.2,"target_profit_pct":0.35}', 'small_tier_v1', '[]', 'Anchor: verbatim policy_lab_cohorts.policy_config for the neutral cohort (shadow-only (never promoted)); no axis varied.', 'fable_orchestrator_lane_a'),
    ('conservative_anchor', 'conservative', 'conservative_anchor', '{"budget_cap_pct":0.25,"max_dte_to_enter":45,"max_positions_open":2,"max_risk_pct_per_trade":0.015,"max_suggestions_per_day":2,"min_dte_to_exit":14,"min_score_threshold":70.0,"risk_multiplier":0.8,"sizing_method":"budget_proportional","stop_loss_pct":0.15,"target_profit_pct":0.25}', 'small_tier_v1', '[]', 'Anchor: verbatim policy_lab_cohorts.policy_config for the conservative cohort (shadow-only (never promoted)); no axis varied.', 'fable_orchestrator_lane_a'),
    ('agg_budget025_v1', 'aggressive', 'aggressive_anchor', '{"budget_cap_pct":0.25,"max_dte_to_enter":45,"max_positions_open":4,"max_risk_pct_per_trade":0.035,"max_suggestions_per_day":4,"min_dte_to_exit":7,"min_score_threshold":30.0,"risk_multiplier":1.2,"sizing_method":"budget_proportional","stop_loss_pct":0.3,"target_profit_pct":0.5}', 'small_tier_v1', '["budget_cap_pct"]', 'aggressive anchor with budget_cap_pct 0.35->0.25 (lowered; hull [0.25,0.35])', 'fable_orchestrator_lane_a'),
    ('agg_pos2_v1', 'aggressive', 'aggressive_anchor', '{"budget_cap_pct":0.35,"max_dte_to_enter":45,"max_positions_open":2,"max_risk_pct_per_trade":0.035,"max_suggestions_per_day":4,"min_dte_to_exit":7,"min_score_threshold":30.0,"risk_multiplier":1.2,"sizing_method":"budget_proportional","stop_loss_pct":0.3,"target_profit_pct":0.5}', 'small_tier_v1', '["max_positions_open"]', 'aggressive anchor with max_positions_open 4->2 (lowered; hull [2,4])', 'fable_orchestrator_lane_a'),
    ('agg_riskpct025_v1', 'aggressive', 'aggressive_anchor', '{"budget_cap_pct":0.35,"max_dte_to_enter":45,"max_positions_open":4,"max_risk_pct_per_trade":0.025,"max_suggestions_per_day":4,"min_dte_to_exit":7,"min_score_threshold":30.0,"risk_multiplier":1.2,"sizing_method":"budget_proportional","stop_loss_pct":0.3,"target_profit_pct":0.5}', 'small_tier_v1', '["max_risk_pct_per_trade"]', 'aggressive anchor with max_risk_pct_per_trade 0.035->0.025 (lowered; hull [0.015,0.035])', 'fable_orchestrator_lane_a'),
    ('agg_sugg2_v1', 'aggressive', 'aggressive_anchor', '{"budget_cap_pct":0.35,"max_dte_to_enter":45,"max_positions_open":4,"max_risk_pct_per_trade":0.035,"max_suggestions_per_day":2,"min_dte_to_exit":7,"min_score_threshold":30.0,"risk_multiplier":1.2,"sizing_method":"budget_proportional","stop_loss_pct":0.3,"target_profit_pct":0.5}', 'small_tier_v1', '["max_suggestions_per_day"]', 'aggressive anchor with max_suggestions_per_day 4->2 (lowered; hull [2,4])', 'fable_orchestrator_lane_a'),
    ('agg_dteexit10_v1', 'aggressive', 'aggressive_anchor', '{"budget_cap_pct":0.35,"max_dte_to_enter":45,"max_positions_open":4,"max_risk_pct_per_trade":0.035,"max_suggestions_per_day":4,"min_dte_to_exit":10,"min_score_threshold":30.0,"risk_multiplier":1.2,"sizing_method":"budget_proportional","stop_loss_pct":0.3,"target_profit_pct":0.5}', 'small_tier_v1', '["min_dte_to_exit"]', 'aggressive anchor with min_dte_to_exit 7->10 (raised; hull [7,14])', 'fable_orchestrator_lane_a'),
    ('agg_score50_v1', 'aggressive', 'aggressive_anchor', '{"budget_cap_pct":0.35,"max_dte_to_enter":45,"max_positions_open":4,"max_risk_pct_per_trade":0.035,"max_suggestions_per_day":4,"min_dte_to_exit":7,"min_score_threshold":50.0,"risk_multiplier":1.2,"sizing_method":"budget_proportional","stop_loss_pct":0.3,"target_profit_pct":0.5}', 'small_tier_v1', '["min_score_threshold"]', 'aggressive anchor with min_score_threshold 30->50 (raised; hull [30,70])', 'fable_orchestrator_lane_a'),
    ('agg_score70_v1', 'aggressive', 'aggressive_anchor', '{"budget_cap_pct":0.35,"max_dte_to_enter":45,"max_positions_open":4,"max_risk_pct_per_trade":0.035,"max_suggestions_per_day":4,"min_dte_to_exit":7,"min_score_threshold":70.0,"risk_multiplier":1.2,"sizing_method":"budget_proportional","stop_loss_pct":0.3,"target_profit_pct":0.5}', 'small_tier_v1', '["min_score_threshold"]', 'aggressive anchor with min_score_threshold 30->70 (raised; hull [30,70])', 'fable_orchestrator_lane_a'),
    ('agg_mult080_v1', 'aggressive', 'aggressive_anchor', '{"budget_cap_pct":0.35,"max_dte_to_enter":45,"max_positions_open":4,"max_risk_pct_per_trade":0.035,"max_suggestions_per_day":4,"min_dte_to_exit":7,"min_score_threshold":30.0,"risk_multiplier":0.8,"sizing_method":"budget_proportional","stop_loss_pct":0.3,"target_profit_pct":0.5}', 'small_tier_v1', '["risk_multiplier"]', 'aggressive anchor with risk_multiplier 1.2->0.8 (lowered; hull [0.8,1.2])', 'fable_orchestrator_lane_a'),
    ('agg_mult100_v1', 'aggressive', 'aggressive_anchor', '{"budget_cap_pct":0.35,"max_dte_to_enter":45,"max_positions_open":4,"max_risk_pct_per_trade":0.035,"max_suggestions_per_day":4,"min_dte_to_exit":7,"min_score_threshold":30.0,"risk_multiplier":1.0,"sizing_method":"budget_proportional","stop_loss_pct":0.3,"target_profit_pct":0.5}', 'small_tier_v1', '["risk_multiplier"]', 'aggressive anchor with risk_multiplier 1.2->1 (lowered; hull [0.8,1.2])', 'fable_orchestrator_lane_a'),
    ('agg_stop015_v1', 'aggressive', 'aggressive_anchor', '{"budget_cap_pct":0.35,"max_dte_to_enter":45,"max_positions_open":4,"max_risk_pct_per_trade":0.035,"max_suggestions_per_day":4,"min_dte_to_exit":7,"min_score_threshold":30.0,"risk_multiplier":1.2,"sizing_method":"budget_proportional","stop_loss_pct":0.15,"target_profit_pct":0.5}', 'small_tier_v1', '["stop_loss_pct"]', 'aggressive anchor with stop_loss_pct 0.3->0.15 (lowered; hull [0.15,0.3])', 'fable_orchestrator_lane_a'),
    ('agg_stop020_v1', 'aggressive', 'aggressive_anchor', '{"budget_cap_pct":0.35,"max_dte_to_enter":45,"max_positions_open":4,"max_risk_pct_per_trade":0.035,"max_suggestions_per_day":4,"min_dte_to_exit":7,"min_score_threshold":30.0,"risk_multiplier":1.2,"sizing_method":"budget_proportional","stop_loss_pct":0.2,"target_profit_pct":0.5}', 'small_tier_v1', '["stop_loss_pct"]', 'aggressive anchor with stop_loss_pct 0.3->0.2 (lowered; hull [0.15,0.3])', 'fable_orchestrator_lane_a'),
    ('agg_tp025_v1', 'aggressive', 'aggressive_anchor', '{"budget_cap_pct":0.35,"max_dte_to_enter":45,"max_positions_open":4,"max_risk_pct_per_trade":0.035,"max_suggestions_per_day":4,"min_dte_to_exit":7,"min_score_threshold":30.0,"risk_multiplier":1.2,"sizing_method":"budget_proportional","stop_loss_pct":0.3,"target_profit_pct":0.25}', 'small_tier_v1', '["target_profit_pct"]', 'aggressive anchor with target_profit_pct 0.5->0.25 (lowered; hull [0.25,0.5])', 'fable_orchestrator_lane_a'),
    ('agg_tp035_v1', 'aggressive', 'aggressive_anchor', '{"budget_cap_pct":0.35,"max_dte_to_enter":45,"max_positions_open":4,"max_risk_pct_per_trade":0.035,"max_suggestions_per_day":4,"min_dte_to_exit":7,"min_score_threshold":30.0,"risk_multiplier":1.2,"sizing_method":"budget_proportional","stop_loss_pct":0.3,"target_profit_pct":0.35}', 'small_tier_v1', '["target_profit_pct"]', 'aggressive anchor with target_profit_pct 0.5->0.35 (lowered; hull [0.25,0.5])', 'fable_orchestrator_lane_a'),
    ('neu_budget035_v1', 'neutral', 'neutral_anchor', '{"budget_cap_pct":0.35,"max_dte_to_enter":45,"max_positions_open":3,"max_risk_pct_per_trade":0.025,"max_suggestions_per_day":3,"min_dte_to_exit":10,"min_score_threshold":50.0,"risk_multiplier":1.0,"sizing_method":"budget_proportional","stop_loss_pct":0.2,"target_profit_pct":0.35}', 'small_tier_v1', '["budget_cap_pct"]', 'neutral anchor with budget_cap_pct 0.3->0.35 (raised; hull [0.25,0.35])', 'fable_orchestrator_lane_a'),
    ('neu_pos4_v1', 'neutral', 'neutral_anchor', '{"budget_cap_pct":0.3,"max_dte_to_enter":45,"max_positions_open":4,"max_risk_pct_per_trade":0.025,"max_suggestions_per_day":3,"min_dte_to_exit":10,"min_score_threshold":50.0,"risk_multiplier":1.0,"sizing_method":"budget_proportional","stop_loss_pct":0.2,"target_profit_pct":0.35}', 'small_tier_v1', '["max_positions_open"]', 'neutral anchor with max_positions_open 3->4 (raised; hull [2,4])', 'fable_orchestrator_lane_a'),
    ('neu_riskpct035_v1', 'neutral', 'neutral_anchor', '{"budget_cap_pct":0.3,"max_dte_to_enter":45,"max_positions_open":3,"max_risk_pct_per_trade":0.035,"max_suggestions_per_day":3,"min_dte_to_exit":10,"min_score_threshold":50.0,"risk_multiplier":1.0,"sizing_method":"budget_proportional","stop_loss_pct":0.2,"target_profit_pct":0.35}', 'small_tier_v1', '["max_risk_pct_per_trade"]', 'neutral anchor with max_risk_pct_per_trade 0.025->0.035 (raised; hull [0.015,0.035])', 'fable_orchestrator_lane_a'),
    ('neu_sugg4_v1', 'neutral', 'neutral_anchor', '{"budget_cap_pct":0.3,"max_dte_to_enter":45,"max_positions_open":3,"max_risk_pct_per_trade":0.025,"max_suggestions_per_day":4,"min_dte_to_exit":10,"min_score_threshold":50.0,"risk_multiplier":1.0,"sizing_method":"budget_proportional","stop_loss_pct":0.2,"target_profit_pct":0.35}', 'small_tier_v1', '["max_suggestions_per_day"]', 'neutral anchor with max_suggestions_per_day 3->4 (raised; hull [2,4])', 'fable_orchestrator_lane_a'),
    ('neu_dteexit14_v1', 'neutral', 'neutral_anchor', '{"budget_cap_pct":0.3,"max_dte_to_enter":45,"max_positions_open":3,"max_risk_pct_per_trade":0.025,"max_suggestions_per_day":3,"min_dte_to_exit":14,"min_score_threshold":50.0,"risk_multiplier":1.0,"sizing_method":"budget_proportional","stop_loss_pct":0.2,"target_profit_pct":0.35}', 'small_tier_v1', '["min_dte_to_exit"]', 'neutral anchor with min_dte_to_exit 10->14 (raised; hull [7,14])', 'fable_orchestrator_lane_a'),
    ('neu_score30_v1', 'neutral', 'neutral_anchor', '{"budget_cap_pct":0.3,"max_dte_to_enter":45,"max_positions_open":3,"max_risk_pct_per_trade":0.025,"max_suggestions_per_day":3,"min_dte_to_exit":10,"min_score_threshold":30.0,"risk_multiplier":1.0,"sizing_method":"budget_proportional","stop_loss_pct":0.2,"target_profit_pct":0.35}', 'small_tier_v1', '["min_score_threshold"]', 'neutral anchor with min_score_threshold 50->30 (lowered; hull [30,70])', 'fable_orchestrator_lane_a'),
    ('neu_score70_v1', 'neutral', 'neutral_anchor', '{"budget_cap_pct":0.3,"max_dte_to_enter":45,"max_positions_open":3,"max_risk_pct_per_trade":0.025,"max_suggestions_per_day":3,"min_dte_to_exit":10,"min_score_threshold":70.0,"risk_multiplier":1.0,"sizing_method":"budget_proportional","stop_loss_pct":0.2,"target_profit_pct":0.35}', 'small_tier_v1', '["min_score_threshold"]', 'neutral anchor with min_score_threshold 50->70 (raised; hull [30,70])', 'fable_orchestrator_lane_a'),
    ('neu_mult080_v1', 'neutral', 'neutral_anchor', '{"budget_cap_pct":0.3,"max_dte_to_enter":45,"max_positions_open":3,"max_risk_pct_per_trade":0.025,"max_suggestions_per_day":3,"min_dte_to_exit":10,"min_score_threshold":50.0,"risk_multiplier":0.8,"sizing_method":"budget_proportional","stop_loss_pct":0.2,"target_profit_pct":0.35}', 'small_tier_v1', '["risk_multiplier"]', 'neutral anchor with risk_multiplier 1->0.8 (lowered; hull [0.8,1.2])', 'fable_orchestrator_lane_a'),
    ('neu_mult120_v1', 'neutral', 'neutral_anchor', '{"budget_cap_pct":0.3,"max_dte_to_enter":45,"max_positions_open":3,"max_risk_pct_per_trade":0.025,"max_suggestions_per_day":3,"min_dte_to_exit":10,"min_score_threshold":50.0,"risk_multiplier":1.2,"sizing_method":"budget_proportional","stop_loss_pct":0.2,"target_profit_pct":0.35}', 'small_tier_v1', '["risk_multiplier"]', 'neutral anchor with risk_multiplier 1->1.2 (raised; hull [0.8,1.2])', 'fable_orchestrator_lane_a'),
    ('neu_stop015_v1', 'neutral', 'neutral_anchor', '{"budget_cap_pct":0.3,"max_dte_to_enter":45,"max_positions_open":3,"max_risk_pct_per_trade":0.025,"max_suggestions_per_day":3,"min_dte_to_exit":10,"min_score_threshold":50.0,"risk_multiplier":1.0,"sizing_method":"budget_proportional","stop_loss_pct":0.15,"target_profit_pct":0.35}', 'small_tier_v1', '["stop_loss_pct"]', 'neutral anchor with stop_loss_pct 0.2->0.15 (lowered; hull [0.15,0.3])', 'fable_orchestrator_lane_a'),
    ('neu_stop030_v1', 'neutral', 'neutral_anchor', '{"budget_cap_pct":0.3,"max_dte_to_enter":45,"max_positions_open":3,"max_risk_pct_per_trade":0.025,"max_suggestions_per_day":3,"min_dte_to_exit":10,"min_score_threshold":50.0,"risk_multiplier":1.0,"sizing_method":"budget_proportional","stop_loss_pct":0.3,"target_profit_pct":0.35}', 'small_tier_v1', '["stop_loss_pct"]', 'neutral anchor with stop_loss_pct 0.2->0.3 (raised; hull [0.15,0.3])', 'fable_orchestrator_lane_a'),
    ('neu_tp025_v1', 'neutral', 'neutral_anchor', '{"budget_cap_pct":0.3,"max_dte_to_enter":45,"max_positions_open":3,"max_risk_pct_per_trade":0.025,"max_suggestions_per_day":3,"min_dte_to_exit":10,"min_score_threshold":50.0,"risk_multiplier":1.0,"sizing_method":"budget_proportional","stop_loss_pct":0.2,"target_profit_pct":0.25}', 'small_tier_v1', '["target_profit_pct"]', 'neutral anchor with target_profit_pct 0.35->0.25 (lowered; hull [0.25,0.5])', 'fable_orchestrator_lane_a'),
    ('neu_tp050_v1', 'neutral', 'neutral_anchor', '{"budget_cap_pct":0.3,"max_dte_to_enter":45,"max_positions_open":3,"max_risk_pct_per_trade":0.025,"max_suggestions_per_day":3,"min_dte_to_exit":10,"min_score_threshold":50.0,"risk_multiplier":1.0,"sizing_method":"budget_proportional","stop_loss_pct":0.2,"target_profit_pct":0.5}', 'small_tier_v1', '["target_profit_pct"]', 'neutral anchor with target_profit_pct 0.35->0.5 (raised; hull [0.25,0.5])', 'fable_orchestrator_lane_a'),
    ('con_budget035_v1', 'conservative', 'conservative_anchor', '{"budget_cap_pct":0.35,"max_dte_to_enter":45,"max_positions_open":2,"max_risk_pct_per_trade":0.015,"max_suggestions_per_day":2,"min_dte_to_exit":14,"min_score_threshold":70.0,"risk_multiplier":0.8,"sizing_method":"budget_proportional","stop_loss_pct":0.15,"target_profit_pct":0.25}', 'small_tier_v1', '["budget_cap_pct"]', 'conservative anchor with budget_cap_pct 0.25->0.35 (raised; hull [0.25,0.35])', 'fable_orchestrator_lane_a'),
    ('con_pos3_v1', 'conservative', 'conservative_anchor', '{"budget_cap_pct":0.25,"max_dte_to_enter":45,"max_positions_open":3,"max_risk_pct_per_trade":0.015,"max_suggestions_per_day":2,"min_dte_to_exit":14,"min_score_threshold":70.0,"risk_multiplier":0.8,"sizing_method":"budget_proportional","stop_loss_pct":0.15,"target_profit_pct":0.25}', 'small_tier_v1', '["max_positions_open"]', 'conservative anchor with max_positions_open 2->3 (raised; hull [2,4])', 'fable_orchestrator_lane_a'),
    ('con_riskpct025_v1', 'conservative', 'conservative_anchor', '{"budget_cap_pct":0.25,"max_dte_to_enter":45,"max_positions_open":2,"max_risk_pct_per_trade":0.025,"max_suggestions_per_day":2,"min_dte_to_exit":14,"min_score_threshold":70.0,"risk_multiplier":0.8,"sizing_method":"budget_proportional","stop_loss_pct":0.15,"target_profit_pct":0.25}', 'small_tier_v1', '["max_risk_pct_per_trade"]', 'conservative anchor with max_risk_pct_per_trade 0.015->0.025 (raised; hull [0.015,0.035])', 'fable_orchestrator_lane_a'),
    ('con_sugg3_v1', 'conservative', 'conservative_anchor', '{"budget_cap_pct":0.25,"max_dte_to_enter":45,"max_positions_open":2,"max_risk_pct_per_trade":0.015,"max_suggestions_per_day":3,"min_dte_to_exit":14,"min_score_threshold":70.0,"risk_multiplier":0.8,"sizing_method":"budget_proportional","stop_loss_pct":0.15,"target_profit_pct":0.25}', 'small_tier_v1', '["max_suggestions_per_day"]', 'conservative anchor with max_suggestions_per_day 2->3 (raised; hull [2,4])', 'fable_orchestrator_lane_a'),
    ('con_dteexit10_v1', 'conservative', 'conservative_anchor', '{"budget_cap_pct":0.25,"max_dte_to_enter":45,"max_positions_open":2,"max_risk_pct_per_trade":0.015,"max_suggestions_per_day":2,"min_dte_to_exit":10,"min_score_threshold":70.0,"risk_multiplier":0.8,"sizing_method":"budget_proportional","stop_loss_pct":0.15,"target_profit_pct":0.25}', 'small_tier_v1', '["min_dte_to_exit"]', 'conservative anchor with min_dte_to_exit 14->10 (lowered; hull [7,14])', 'fable_orchestrator_lane_a'),
    ('con_score30_v1', 'conservative', 'conservative_anchor', '{"budget_cap_pct":0.25,"max_dte_to_enter":45,"max_positions_open":2,"max_risk_pct_per_trade":0.015,"max_suggestions_per_day":2,"min_dte_to_exit":14,"min_score_threshold":30.0,"risk_multiplier":0.8,"sizing_method":"budget_proportional","stop_loss_pct":0.15,"target_profit_pct":0.25}', 'small_tier_v1', '["min_score_threshold"]', 'conservative anchor with min_score_threshold 70->30 (lowered; hull [30,70])', 'fable_orchestrator_lane_a'),
    ('con_score50_v1', 'conservative', 'conservative_anchor', '{"budget_cap_pct":0.25,"max_dte_to_enter":45,"max_positions_open":2,"max_risk_pct_per_trade":0.015,"max_suggestions_per_day":2,"min_dte_to_exit":14,"min_score_threshold":50.0,"risk_multiplier":0.8,"sizing_method":"budget_proportional","stop_loss_pct":0.15,"target_profit_pct":0.25}', 'small_tier_v1', '["min_score_threshold"]', 'conservative anchor with min_score_threshold 70->50 (lowered; hull [30,70])', 'fable_orchestrator_lane_a'),
    ('con_mult100_v1', 'conservative', 'conservative_anchor', '{"budget_cap_pct":0.25,"max_dte_to_enter":45,"max_positions_open":2,"max_risk_pct_per_trade":0.015,"max_suggestions_per_day":2,"min_dte_to_exit":14,"min_score_threshold":70.0,"risk_multiplier":1.0,"sizing_method":"budget_proportional","stop_loss_pct":0.15,"target_profit_pct":0.25}', 'small_tier_v1', '["risk_multiplier"]', 'conservative anchor with risk_multiplier 0.8->1 (raised; hull [0.8,1.2])', 'fable_orchestrator_lane_a'),
    ('con_mult120_v1', 'conservative', 'conservative_anchor', '{"budget_cap_pct":0.25,"max_dte_to_enter":45,"max_positions_open":2,"max_risk_pct_per_trade":0.015,"max_suggestions_per_day":2,"min_dte_to_exit":14,"min_score_threshold":70.0,"risk_multiplier":1.2,"sizing_method":"budget_proportional","stop_loss_pct":0.15,"target_profit_pct":0.25}', 'small_tier_v1', '["risk_multiplier"]', 'conservative anchor with risk_multiplier 0.8->1.2 (raised; hull [0.8,1.2])', 'fable_orchestrator_lane_a'),
    ('con_stop020_v1', 'conservative', 'conservative_anchor', '{"budget_cap_pct":0.25,"max_dte_to_enter":45,"max_positions_open":2,"max_risk_pct_per_trade":0.015,"max_suggestions_per_day":2,"min_dte_to_exit":14,"min_score_threshold":70.0,"risk_multiplier":0.8,"sizing_method":"budget_proportional","stop_loss_pct":0.2,"target_profit_pct":0.25}', 'small_tier_v1', '["stop_loss_pct"]', 'conservative anchor with stop_loss_pct 0.15->0.2 (raised; hull [0.15,0.3])', 'fable_orchestrator_lane_a'),
    ('con_stop030_v1', 'conservative', 'conservative_anchor', '{"budget_cap_pct":0.25,"max_dte_to_enter":45,"max_positions_open":2,"max_risk_pct_per_trade":0.015,"max_suggestions_per_day":2,"min_dte_to_exit":14,"min_score_threshold":70.0,"risk_multiplier":0.8,"sizing_method":"budget_proportional","stop_loss_pct":0.3,"target_profit_pct":0.25}', 'small_tier_v1', '["stop_loss_pct"]', 'conservative anchor with stop_loss_pct 0.15->0.3 (raised; hull [0.15,0.3])', 'fable_orchestrator_lane_a'),
    ('con_tp035_v1', 'conservative', 'conservative_anchor', '{"budget_cap_pct":0.25,"max_dte_to_enter":45,"max_positions_open":2,"max_risk_pct_per_trade":0.015,"max_suggestions_per_day":2,"min_dte_to_exit":14,"min_score_threshold":70.0,"risk_multiplier":0.8,"sizing_method":"budget_proportional","stop_loss_pct":0.15,"target_profit_pct":0.35}', 'small_tier_v1', '["target_profit_pct"]', 'conservative anchor with target_profit_pct 0.25->0.35 (raised; hull [0.25,0.5])', 'fable_orchestrator_lane_a'),
    ('con_tp050_v1', 'conservative', 'conservative_anchor', '{"budget_cap_pct":0.25,"max_dte_to_enter":45,"max_positions_open":2,"max_risk_pct_per_trade":0.015,"max_suggestions_per_day":2,"min_dte_to_exit":14,"min_score_threshold":70.0,"risk_multiplier":0.8,"sizing_method":"budget_proportional","stop_loss_pct":0.15,"target_profit_pct":0.5}', 'small_tier_v1', '["target_profit_pct"]', 'conservative anchor with target_profit_pct 0.25->0.5 (raised; hull [0.25,0.5])', 'fable_orchestrator_lane_a'),
    ('agg_stop025_tp040_v1', 'aggressive', 'aggressive_anchor', '{"budget_cap_pct":0.35,"max_dte_to_enter":45,"max_positions_open":4,"max_risk_pct_per_trade":0.035,"max_suggestions_per_day":4,"min_dte_to_exit":7,"min_score_threshold":30.0,"risk_multiplier":1.2,"sizing_method":"budget_proportional","stop_loss_pct":0.25,"target_profit_pct":0.4}', 'small_tier_v1', '["stop_loss_pct","target_profit_pct"]', 'aggressive anchor with stop_loss_pct 0.3->0.25 (lowered; hull [0.15,0.3]); target_profit_pct 0.5->0.4 (lowered; hull [0.25,0.5])', 'fable_orchestrator_lane_a'),
    ('agg_budget030_mult100_v1', 'aggressive', 'aggressive_anchor', '{"budget_cap_pct":0.3,"max_dte_to_enter":45,"max_positions_open":4,"max_risk_pct_per_trade":0.035,"max_suggestions_per_day":4,"min_dte_to_exit":7,"min_score_threshold":30.0,"risk_multiplier":1.0,"sizing_method":"budget_proportional","stop_loss_pct":0.3,"target_profit_pct":0.5}', 'small_tier_v1', '["budget_cap_pct","risk_multiplier"]', 'aggressive anchor with budget_cap_pct 0.35->0.3 (lowered; hull [0.25,0.35]); risk_multiplier 1.2->1 (lowered; hull [0.8,1.2])', 'fable_orchestrator_lane_a'),
    ('agg_pos3_score50_v1', 'aggressive', 'aggressive_anchor', '{"budget_cap_pct":0.35,"max_dte_to_enter":45,"max_positions_open":3,"max_risk_pct_per_trade":0.035,"max_suggestions_per_day":4,"min_dte_to_exit":7,"min_score_threshold":50.0,"risk_multiplier":1.2,"sizing_method":"budget_proportional","stop_loss_pct":0.3,"target_profit_pct":0.5}', 'small_tier_v1', '["max_positions_open","min_score_threshold"]', 'aggressive anchor with max_positions_open 4->3 (lowered; hull [2,4]); min_score_threshold 30->50 (raised; hull [30,70])', 'fable_orchestrator_lane_a'),
    ('neu_stop015_tp025_v1', 'neutral', 'neutral_anchor', '{"budget_cap_pct":0.3,"max_dte_to_enter":45,"max_positions_open":3,"max_risk_pct_per_trade":0.025,"max_suggestions_per_day":3,"min_dte_to_exit":10,"min_score_threshold":50.0,"risk_multiplier":1.0,"sizing_method":"budget_proportional","stop_loss_pct":0.15,"target_profit_pct":0.25}', 'small_tier_v1', '["stop_loss_pct","target_profit_pct"]', 'neutral anchor with stop_loss_pct 0.2->0.15 (lowered; hull [0.15,0.3]); target_profit_pct 0.35->0.25 (lowered; hull [0.25,0.5])', 'fable_orchestrator_lane_a'),
    ('neu_budget035_mult120_v1', 'neutral', 'neutral_anchor', '{"budget_cap_pct":0.35,"max_dte_to_enter":45,"max_positions_open":3,"max_risk_pct_per_trade":0.025,"max_suggestions_per_day":3,"min_dte_to_exit":10,"min_score_threshold":50.0,"risk_multiplier":1.2,"sizing_method":"budget_proportional","stop_loss_pct":0.2,"target_profit_pct":0.35}', 'small_tier_v1', '["budget_cap_pct","risk_multiplier"]', 'neutral anchor with budget_cap_pct 0.3->0.35 (raised; hull [0.25,0.35]); risk_multiplier 1->1.2 (raised; hull [0.8,1.2])', 'fable_orchestrator_lane_a'),
    ('neu_budget035_riskpct035_v1', 'neutral', 'neutral_anchor', '{"budget_cap_pct":0.35,"max_dte_to_enter":45,"max_positions_open":3,"max_risk_pct_per_trade":0.035,"max_suggestions_per_day":3,"min_dte_to_exit":10,"min_score_threshold":50.0,"risk_multiplier":1.0,"sizing_method":"budget_proportional","stop_loss_pct":0.2,"target_profit_pct":0.35}', 'small_tier_v1', '["budget_cap_pct","max_risk_pct_per_trade"]', 'neutral anchor with budget_cap_pct 0.3->0.35 (raised; hull [0.25,0.35]); max_risk_pct_per_trade 0.025->0.035 (raised; hull [0.015,0.035])', 'fable_orchestrator_lane_a'),
    ('con_stop020_tp035_v1', 'conservative', 'conservative_anchor', '{"budget_cap_pct":0.25,"max_dte_to_enter":45,"max_positions_open":2,"max_risk_pct_per_trade":0.015,"max_suggestions_per_day":2,"min_dte_to_exit":14,"min_score_threshold":70.0,"risk_multiplier":0.8,"sizing_method":"budget_proportional","stop_loss_pct":0.2,"target_profit_pct":0.35}', 'small_tier_v1', '["stop_loss_pct","target_profit_pct"]', 'conservative anchor with stop_loss_pct 0.15->0.2 (raised; hull [0.15,0.3]); target_profit_pct 0.25->0.35 (raised; hull [0.25,0.5])', 'fable_orchestrator_lane_a'),
    ('con_pos3_score50_v1', 'conservative', 'conservative_anchor', '{"budget_cap_pct":0.25,"max_dte_to_enter":45,"max_positions_open":3,"max_risk_pct_per_trade":0.015,"max_suggestions_per_day":2,"min_dte_to_exit":14,"min_score_threshold":50.0,"risk_multiplier":0.8,"sizing_method":"budget_proportional","stop_loss_pct":0.15,"target_profit_pct":0.25}', 'small_tier_v1', '["max_positions_open","min_score_threshold"]', 'conservative anchor with max_positions_open 2->3 (raised; hull [2,4]); min_score_threshold 70->50 (lowered; hull [30,70])', 'fable_orchestrator_lane_a')
) AS v(
    policy_registration_id, policy_family, anchor_lineage,
    config_canonical, effective_epoch, changed_axes,
    design_rationale, created_by
);

-- Post-insert integrity assertions (fail -> ROLLBACK).
DO $$
DECLARE
    v_count int;
    v_distinct_hash int;
    v_distinct_canonical int;
    v_hash_mismatch int;
BEGIN
    SELECT count(*) INTO v_count
      FROM policy_registrations WHERE effective_epoch = 'small_tier_v1';
    IF v_count <> 50 THEN
        RAISE EXCEPTION 'policy_registrations seed: expected 50 rows, got %', v_count;
    END IF;
    SELECT count(DISTINCT config_hash) INTO v_distinct_hash
      FROM policy_registrations WHERE effective_epoch = 'small_tier_v1';
    IF v_distinct_hash <> 50 THEN
        RAISE EXCEPTION 'policy_registrations seed: expected 50 distinct config_hash, got %', v_distinct_hash;
    END IF;
    SELECT count(DISTINCT config_canonical) INTO v_distinct_canonical
      FROM policy_registrations WHERE effective_epoch = 'small_tier_v1';
    IF v_distinct_canonical <> 50 THEN
        RAISE EXCEPTION 'policy_registrations seed: expected 50 distinct config_canonical, got %', v_distinct_canonical;
    END IF;
    SELECT count(*) INTO v_hash_mismatch
      FROM policy_registrations
     WHERE effective_epoch = 'small_tier_v1'
       AND config_hash <> encode(extensions.digest(config_canonical, 'sha256'), 'hex');
    IF v_hash_mismatch <> 0 THEN
        RAISE EXCEPTION 'policy_registrations seed: % rows have config_hash != sha256(config_canonical)', v_hash_mismatch;
    END IF;
END $$;

COMMIT;
